# 基础镜像
FROM redis
# author
MAINTAINER rail

# 挂载目录
VOLUME /home/rail/redis
# 创建目录
RUN mkdir -p /home/rail/redis
# 指定路径
WORKDIR /home/rail/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/rail/redis/redis.conf
