# 基础镜像
FROM redis
# author
MAINTAINER book

# 挂载目录
VOLUME /home/book/redis
# 创建目录
RUN mkdir -p /home/book/redis
# 指定路径
WORKDIR /home/book/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/book/redis/redis.conf
