# 基础镜像
FROM  openjdk:17
# author
MAINTAINER rail

# 挂载目录
VOLUME /home/rail
# 创建目录
RUN mkdir -p /home/rail
# 指定路径
WORKDIR /home/rail
# 复制jar文件到路径
COPY ./jar/rail-modules-file.jar /home/rail/rail-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","rail-modules-file.jar"]