# 基础镜像
FROM nginx
# author
MAINTAINER rail

# 挂载目录
VOLUME /home/rail/projects/rail-ui
# 创建目录
RUN mkdir -p /home/rail/projects/rail-ui
# 指定路径
WORKDIR /home/rail/projects/rail-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/rail/projects/rail-ui
