# 基础镜像
FROM nginx
# author
MAINTAINER book

# 挂载目录
VOLUME /home/book/projects/book-ui
# 创建目录
RUN mkdir -p /home/book/projects/book-ui
# 指定路径
WORKDIR /home/book/projects/book-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/book/projects/book-ui
