# 基础镜像
FROM  openjdk:17
# author
MAINTAINER book

# 挂载目录
VOLUME /home/book
# 创建目录
RUN mkdir -p /home/book
# 指定路径
WORKDIR /home/book
# 复制jar文件到路径
COPY ./jar/book-modules-file.jar /home/book/book-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","book-modules-file.jar"]