# 基础镜像
FROM  openjdk:17
# author
MAINTAINER rail

# 挂载目录
VOLUME /home/rail
# 创建目录
RUN mkdir -p /home/rail
# 指定路径
WORKDIR /home/rail
# 复制jar文件到路径
COPY ./jar/rail-auth.jar /home/rail/rail-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","rail-auth.jar"]